name: Build desktop app (Windows)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-win:
    runs-on: windows-latest
    strategy:
      matrix:
        py: ['3.8.10']  # giữ đúng 3.8 cho aicspylibczi

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # Bản tối giản, pin cho Python 3.8
          pip install \
            "numpy<2.0" \
            scikit-image==0.20.0 \
            pillow \
            aicspylibczi \
            opencv-python-headless \
            "pyinstaller<6.0"  # PyInstaller 5.x tương thích Python 3.8

      - name: Build GUI onefile
        shell: bash
        run: |
          ENTRY="Biofilms/src/tool_tkinter.py"
          pyinstaller \
            --noconfirm \
            --clean \
            --onefile \
            --noconsole \
            --name BiofilmsGUI \
            --collect-all aicspylibczi \
            --collect-all tifffile \
            --collect-all imagecodecs \
            --collect-binaries cv2 \
            "$ENTRY"

      - name: Upload artifact (GUI exe)
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: dist/BiofilmsGUI.exe
