name: Build desktop apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]   # add ubuntu-latest , macos-latest later
        py: ['3.8.10']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          # Pin versions compatible with Python 3.8
          pip install \
            "numpy<2.0" \
            "scipy<1.11" \
            "networkx<3.0" \
            scikit-image==0.20.0 \
            pillow \
            imageio \
            czifile \
            aicspylibczi \
            opencv-python-headless \
            pyinstaller

      - name: Build (GUI flags per OS)
        shell: bash
        run: |
          ENTRY="Biofilms/src/tool_tkinter.py"
          # Ensure PyInstaller bundles needed data/binaries
          COMMON_OPTS="--onefile \
            --hidden-import=cv2 \
            --collect-binaries aicspylibczi \
            --collect-data aicspylibczi \
