name: Build desktop apps

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        py: ['3.8.10']
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller czifile imageio numpy

      - name: Build (GUI flags per OS)
        shell: bash
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            pyinstaller --onefile --noconsole Biofilms/src/tool_tkinter.py
          elif [ "$RUNNER_OS" = "macOS" ]; then
            pyinstaller --onefile --windowed Biofilms/src/tool_tkinter.py
          else
            pyinstaller --onefile Biofilms/src/tool_tkinter.py
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ matrix.os }}
          path: dist/*
