name: Build desktop app (Windows & macOS)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-win:
    runs-on: windows-latest
    strategy:
      matrix: { py: ['3.8.10'] }
    steps:
      - uses: actions/checkout@v4

      - name: Write requirements.txt
        shell: bash
        run: |
          cat > requirements.txt << 'EOF'
          numpy<2.0
          scikit-image==0.20.0
          pillow
          aicspylibczi
          tifffile
          imagecodecs
          openpyxl
          opencv-contrib-python-headless
          pyinstaller<6.0
          EOF

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Build (Windows)
        shell: bash
        run: |
          cd Biofilms/src
          ENTRY="tool_tkinter.py"
          python -m PyInstaller \
            --onefile \
            --noconsole \
            --name BioAnalyzer \
            --icon BioAnalyzer.ico \
            --add-data "BioAnalyzer.png;." \
            --add-data "BioAnalyzer.ico;." \
            --collect-all aicspylibczi \
            --collect-all tifffile \
            --collect-all imagecodecs \
            --collect-all cv2 \
            --collect-all openpyxl \
            --hidden-import cv2.ximgproc \
            "$ENTRY"

      - name: Upload artifact (exe)
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: Biofilms/src/dist/BioAnalyzer.exe

  build-macos:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [macos-13, macos-14]   # Intel & Apple Silicon
        py: ['3.8.10']
    steps:
      - uses: actions/checkout@v4

      - name: Write requirements.txt
        shell: bash
        run: |
          cat > requirements.txt << 'EOF'
          numpy<2.0
          scikit-image==0.20.0
          pillow
          aicspylibczi
          tifffile
          imagecodecs
          openpyxl
          opencv-contrib-python-headless
          pyinstaller<6.0
          EOF

      # Fix build-from-source cho imagecodecs trên macOS + Python 3.8
      - name: Install system libs for imagecodecs
        shell: bash
        run: |
          brew update
          brew install libaec libjpeg openjpeg libtiff little-cms2 libpng zstd lz4 webp
          echo "CPPFLAGS=-I$(brew --prefix)/include" >> $GITHUB_ENV
          echo "CFLAGS=-I$(brew --prefix)/include"   >> $GITHUB_ENV
          echo "LDFLAGS=-L$(brew --prefix)/lib"      >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix)/lib/pkgconfig" >> $GITHUB_ENV
          echo "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> $GITHUB_ENV
          echo "MACOSX_DEPLOYMENT_TARGET=11.0" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        shell: bash
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Build (macOS)
        shell: bash
        run: |
          cd Biofilms/src
          ENTRY="tool_tkinter.py"
          ICON_ARG=""
          if [ -f "BioAnalyzer.icns" ]; then ICON_ARG="--icon BioAnalyzer.icns"; fi
          python -m PyInstaller \
            --onefile \
            --windowed \
            --noconsole \
            --name BioAnalyzer \
            ${ICON_ARG} \
            --add-data "BioAnalyzer.png:." \
            --add-data "BioAnalyzer.ico:." \
            --collect-all aicspylibczi \
            --collect-all tifffile \
            --collect-all imagecodecs \
            --collect-all cv2 \
            --collect-all openpyxl \
            --hidden-import cv2.ximgproc \
            "$ENTRY"

      - name: Zip .app
        shell: bash
        run: |
          cd Biofilms/src/dist
          ditto -c -k --sequesterRsrc --keepParent BioAnalyzer.app BioAnalyzer-${{ matrix.runner }}.zip

      - name: Upload artifact (macOS .app)
        uses: actions/upload-artifact@v4
        with:
          name: app-macos-${{ matrix.runner }}
          path: Biofilms/src/dist/BioAnalyzer-${{ matrix.runner }}.zip
